runtime: php74

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|js|woff|woff2|ttf))$
  static_files: public/\1
  upload: .+\.(gif|png|jpg|css|js|woff|woff2|ttf)$


# Serve php scripts.
- url: .*
  script: auto
  
runtime_config:
  document_root: public